<a href="https://colab.research.google.com/github/Ronnie47/Python_libraries/blob/main/Numpy_Notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
myarr = np.array([3,6,37,878,7], np.int64)

In [3]:
myarr

array([  3,   6,  37, 878,   7])

In [4]:
arr = np.array([10, 20, 30, 40, 50])

In [5]:
arr.astype('float64')

array([10., 20., 30., 40., 50.])

In [6]:
a = np.arange(10)
print(a[2:5])

[2 3 4]


In [7]:
arr2 = np.array([20, 10, 40, 30, 50])
print(arr == arr2)

[False False False False  True]


In [8]:
arr1 = np.arange(21,72,2)
arr1

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53,
       55, 57, 59, 61, 63, 65, 67, 69, 71])

In [9]:
print(arr1)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71]


In [10]:
arr = np.array([1,2,3,4,5,6,7,8])
arr[::2] = range(10,50,10)
print(arr)

[10  2 20  4 30  6 40  8]


In [11]:
np.array(['Harry Potter', 1,2,3,4])

array(['Harry Potter', '1', '2', '3', '4'], dtype='<U21')

In [12]:
arr4 = np.array([1,2,3,4], dtype='str')

In [13]:
#typecasting
a = [1,2,3,4]
# can be done using loop or map function

In [14]:
arr4 = arr4.astype('float')

In [15]:
arr4

array([1., 2., 3., 4.])

In [16]:
arr4.dtype

dtype('float64')

In [17]:
arr4 = arr4.astype('int')
print(arr4)
print(arr4.dtype)

[1 2 3 4]
int64


**Getting** Values at Multiple indices in Numpy **bold text**

In [18]:
arr6 = np.arange(100,1001,100)
arr6

array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [19]:
#3rd index, 6th index and 8th index
arr6[[3,6,8]]

array([400, 700, 900])

In [20]:
arr6 + 30

array([ 130,  230,  330,  430,  530,  630,  730,  830,  930, 1030])

In [21]:
arr6 > 500

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [22]:
# Get all the even elements from the list
arr7 = np.arange(1,11)
arr7 % 2 == 0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [23]:
#masking
arr7[[False,  True, False,  True, False,  True, False,  True, False,
        True]]

array([ 2,  4,  6,  8, 10])

In [24]:
#masking == filter operation
arr7[arr7%2==0]

array([ 2,  4,  6,  8, 10])

**What makes numpy fast? vectorisation: executing multiple calculations at the same time**

# NPS(Net Promoter Score) Project

In [37]:
# !wget "https://drive.google.com/file/d/1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK/view" -O nps_data.txt

#the above command and link does not work. I have uploaded the separate file in colab and then perform the NPS

In [38]:
score = np.loadtxt('nps.txt', dtype = 'int64')

In [39]:
print(score)

[10  9  0 ...  8  8  9]


In [40]:
print(type(score))
print(len(score))

<class 'numpy.ndarray'>
5000


In [41]:
promoters = score[score >= 9]

In [42]:
p = promoters.shape
print(p[0])

2309


In [43]:
d = score[score < 7].shape
print(d[0])

1719


In [44]:
t = score.shape
print(t[0])

5000


In [45]:
# NPS = ((#Promoters - #Detractors) / # Total) * 100

NPS = ((p[0] - d[0]) / t[0]) * 100
print(NPS)

11.799999999999999


# Sorting

In [46]:
import numpy as np

In [47]:
a = np.array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])
a

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

In [48]:
b = np.sort(a)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
a # no change is reflected in the original array

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

#### We can directly call `sort` method on array but it can change the original array as it is an inplace operation.

In [50]:
a.sort() # sorting is performed inplace
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Sorting in 2D Array

In [51]:
a = np.array([[1,5,3], [2,5,7], [400, 200, 300]])
a

array([[  1,   5,   3],
       [  2,   5,   7],
       [400, 200, 300]])

In [53]:
np.sort(a, axis=0) # sorting every column

array([[  1,   5,   3],
       [  2,   5,   7],
       [400, 200, 300]])

In [54]:
np.sort(a, axis=1) # sorting every row

array([[  1,   3,   5],
       [  2,   5,   7],
       [200, 300, 400]])

**Note**: By default, the `np.sort()` functions sorts along the last axis.

In [55]:
a = np.array([[23,4,43], [12, 89, 3], [69, 420, 0]])

In [56]:
np.sort(a) # default axis = -1 (last axis)

array([[  4,  23,  43],
       [  3,  12,  89],
       [  0,  69, 420]])

## **Element-Wise Multiplication**

Element-wise multiplication in NumPy involves multiplying corresponding elements of two arrays with the same shape to produce a new array where each element is the product of the corresponding elements from the input arrays.

In [57]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [58]:
a * 5

array([ 5, 10, 15, 20, 25])

In [59]:
b = np.arange(6, 11)
b

array([ 6,  7,  8,  9, 10])

In [60]:
a * b

array([ 6, 14, 24, 36, 50])

Both arrays should have the same shape.

In [61]:
c = np.array([1, 2, 3])

In [62]:
a * c

ValueError: operands could not be broadcast together with shapes (5,) (3,) 

In [63]:
d = np.arange(12).reshape(3, 4)
e = np.arange(13, 25).reshape(3, 4)

In [64]:
print(d)
print(e)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [65]:
d * e

array([[  0,  14,  30,  48],
       [ 68,  90, 114, 140],
       [168, 198, 230, 264]])

In [66]:
d * 5

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

**Takeaway:**

- Array * Number -> WORKS
- Array * Array (same shape) -> WORKS
- Array * Array (different shape) -> DOES NOT WORK

## **Matrix Multiplication**

**Rule:** Number of columns of the first matrix should be equal to number of rows of the second matrix.

- (A,B) * (B,C) -> (A,C)
- (3,4) * (4,3) -> (3,3)

Visual Demo: https://www.geogebra.org/m/ETHXK756

In [67]:
a = np.arange(1,13).reshape((3,4))
c = np.arange(2,14).reshape((4,3))

In [68]:
a.shape, c.shape

((3, 4), (4, 3))

##### `a` is of shape (3,4) and `c` is of shape (4,3). The output will be of shape (3,3).

In [69]:
# Using np.dot
np.dot(a,c)

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [70]:
# Using np.matmul
np.matmul(a,c)

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [71]:
# Using @ operator
a@c

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [72]:
a@5

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [73]:
np.matmul(a, 5)

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [74]:
np.dot(a, 5)

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

**Important:**

- `dot()` function supports the vector multiplication with a scalar value, which is not possible with `matmul()`.
- `Vector * Vector` will work for `matmul()` but `Vector * Scalar` won't.

## **Vectorization**

Vectorization in NumPy refers to performing operations on entire arrays or array elements simultaneously, which is significantly faster and more efficient than using explicit loops.

In [75]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Note:**
- 1d np array --> vector
- 2d np array --> matrix
- 3d onwards --> tensors

In [76]:
def random_operation(x):
    if x % 2 == 0:
        x += 2
    else:
        x -= 2

    return x

In [77]:
random_operation(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [78]:
cool_operation = np.vectorize(random_operation)

In [80]:
cool_operation

In [79]:
type(cool_operation)

numpy.vectorize

#### `np.vectorize()`

- It is a generalised function for vectorization.
- It takes the function and returns an object (which acts like function but can take an array as input and perform the operations).

In [81]:
cool_operation(a)

array([ 2, -1,  4,  1,  6,  3,  8,  5, 10,  7])

## **Broadcasting**

Broadcasting in NumPy is the automatic and implicit extension of array dimensions to enable element-wise operations between arrays with different shapes.

![bro.jpg](https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/047/364/original/download.jpeg?1694345633)

#### **Case 1:** If dimension in both matrix is equal, element-wise addition will be done.

In [82]:
a = np.tile(np.arange(0,40,10), (3,1))
a

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

**Note:**

* `numpy.tile(array, reps)` constructs an array by repeating A the number of times given by reps along each dimension.
* `np.tile(array, (repetition_rows, repetition_cols))`


In [83]:
a=a.T
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [84]:
b = np.tile(np.arange(0,3), (4,1))
b

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [85]:
print(a.shape, b.shape)

(4, 3) (4, 3)


In [86]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

#### **Case 2:** Right array should be of 1-D and number of columns should be same of both the arrays and it will automatically do n-tile.

In [87]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [88]:
c = np.array([0,1,2])
c

array([0, 1, 2])

In [89]:
print(a.shape, c.shape)

(4, 3) (3,)


In [90]:
a + c

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

- c was broadcasted along rows (vertically)
- so that a and c can be made compatible

#### **Case 3:** If the left array is column matrix (must have only 1 column) and right array is row matrix, then it will do the n-tile such that element wise addition is possible.

In [91]:
d = np.array([0,10,20,30]).reshape(4,1)
d

array([[ 0],
       [10],
       [20],
       [30]])

In [92]:
c = np.array([0,1,2])
c

array([0, 1, 2])

In [93]:
print(d.shape, c.shape)

(4, 1) (3,)


In [94]:
d + c

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

- d was stacked (broadcasted) along columns (horizontally)
- c was stacked (broadcasted) along rows (vertically)

**Will broadcasting work in this case?**

In [95]:
a = np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [96]:
b = np.arange(16).reshape(4,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### Broadcasting in 2D Arrays

- A + A (same shape)-> Works
- A + A (1D) -> Works
- A + number -> Works
- A + A (different shape but still 2D) -> DOES NOT WORK

**Is broadcasting possible in this case?**

In [97]:
A = np.arange(1,10).reshape(3,3)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
B = np.array([-1, 0, 1])
B

array([-1,  0,  1])

In [99]:
A*B

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

Yes! Broadcasting is possible for all the operations.


In [100]:
A = np.arange(12).reshape(3, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
B = np.array([1, 2, 3])
B

array([1, 2, 3])

In [102]:
A + B

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

**Why did it throw an error?**

Are the number of dimensions same for both array? No.
- Shape of A $\Rightarrow$ (3,4)
- Shape of B $\Rightarrow$ (3,)

So, `Rule 1` will be invoked to pad 1 to the shape of B.

So, the shape of B becomes **(1,3)**.

\
Now, we check whether broadcasting conditions are met or not?

Starting from the right most side,
- Right most dimension is not equal (4 and 3).

Hence, broadcasting is not possible as per `Rule 3`.

**Question:** Given two arrays,
1. Array A of shape  (8, 1, 6, 1)
2. Array B of shape (7, 1, 5)

Is broadcasting possible in this case? If yes, what will be the shape of output?

**Answer:** Broadcasting possible; Shape will be (8, 7, 6, 5)

**Explanation:**

As number of dimensions are not equal, `Rule 1` is invoked.

The shape of B becomes (1, 7, 1, 5)

Next, it checks whether broadcasting is possible.

A $\Rightarrow$ (8 , 1, 6, 1) \
B $\Rightarrow$ (1, 7, 1, 5)

- Right most dimension, one of the dimension is 1 (1 vs 5)
- Next, comparing 6 and 1, We have one dimension as 1
- Similarly, we have one of the dimension as 1 in both leading dimensions.

Hence, broadcasting is possible.

Now, as per `Rule 2`, dimension with value 1 is streched to match dimension of other array.

- Right most dimension of array is streched to match 5
- Leading dimension of array B (1) is streched to match array A dim (6)

So, the output shape becomes : `(8, 7, 6, 5)`.

# NumPy - 4

In [103]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [104]:
b = a.reshape(2,2)
b

array([[0, 1],
       [2, 3]])

In [105]:
a[0] = 100
a

array([100,   1,   2,   3])

In [106]:
b

array([[100,   1],
       [  2,   3]])

# Shallow Copy

In [107]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [108]:
c = a + 2
c

array([2, 3, 4, 5])

In [109]:
np.shares_memory(a,c)

False

In [110]:
x = 2
y = x #deep copy

x = 3
print(x,y)

3 2


In [111]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
b = a[::2] #shallow copy
b

array([0, 2, 4, 6, 8])

In [113]:
np.shares_memory(a,b)

True

In [114]:
a[0] = 100
a

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [115]:
b

array([100,   2,   4,   6,   8])

In [116]:
# does slicing in base python create deep or shallow copies? Please check

In [117]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [118]:
b = a[a % 1==0] # masking is deep copy operation
b

array([0, 1, 2, 3, 4, 5])

In [119]:

np.shares_memory(a,b)

False

In [120]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
b = a.view() #shallow copy of a
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
np.shares_memory(a,b)

True

In [123]:
#quiz
a = np.array([0,1,2,3,4,5])
b = a[a%1 == 0]
b[0] = 10

In [124]:
a[:2]

array([0, 1])

In [125]:
b = a.view() #shallow copy of a
b

array([0, 1, 2, 3, 4, 5])

In [126]:
b[3] = 45
b

array([ 0,  1,  2, 45,  4,  5])

In [127]:
a

array([ 0,  1,  2, 45,  4,  5])

In [128]:
np.shares_memory(a,b)

True

In [129]:
a = np.arange(10)

In [130]:
b = a.copy() #Deep copy
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
np.shares_memory(a,b)

False

In [132]:
b[1] = 100
b

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9])

In [133]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
a = np.array([1,2,3,[4,5]])
a

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [135]:
b = a.copy()
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [136]:
np.shares_memory(a,b)

False

# Array Splitting

In [137]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [138]:
a,b,c = np.split(x,3)

In [139]:
type(np.split(x,3))

list

In [140]:
np.shares_memory(a,b)

False

In [141]:
np.shares_memory(x,a)

True

In [142]:
b = np.arange(10)
a = np.split(b,3)

ValueError: array split does not result in an equal division

In [143]:
b[0:-1]
np.split(b[0:-1],3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [144]:
c = np.arange(16)

In [145]:
np.split(c, [3,5,6])

[array([0, 1, 2]),
 array([3, 4]),
 array([5]),
 array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])]

In [146]:
np.split(c, [3,20])

[array([0, 1, 2]),
 array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]),
 array([], dtype=int64)]

In [147]:
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [148]:
np.hsplit(x, 2)

[array([[ 0.,  1.],
        [ 4.,  5.],
        [ 8.,  9.],
        [12., 13.]]),
 array([[ 2.,  3.],
        [ 6.,  7.],
        [10., 11.],
        [14., 15.]])]

In [149]:
np.hsplit(x, np.array([ 3, 6]))

[array([[ 0.,  1.,  2.],
        [ 4.,  5.,  6.],
        [ 8.,  9., 10.],
        [12., 13., 14.]]),
 array([[ 3.],
        [ 7.],
        [11.],
        [15.]]),
 array([], shape=(4, 0), dtype=float64)]

In [150]:
x = np.arange(16.0).reshape(4, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [151]:
np.vsplit(x, 2)

[array([[0., 1., 2., 3.],
        [4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])]

# Stacking

In [152]:
a = np.arange(1, 5)
b = np.arange(2, 6)
c = np.arange(3, 7)

In [153]:
np.vstack([a,b,c])

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [154]:
a = np.arange(1, 5)
b = np.arange(2, 4)
c = np.arange(3, 10)

In [155]:
np.vstack([a,b,c])

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 2

In [156]:
#quiz
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])
np.vstack((a, b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [157]:
a = np.arange(5).reshape(5, 1)
a

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [158]:
b = np.arange(15).reshape(5, 3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [159]:
np.hstack([a,b])

array([[ 0,  0,  1,  2],
       [ 1,  3,  4,  5],
       [ 2,  6,  7,  8],
       [ 3,  9, 10, 11],
       [ 4, 12, 13, 14]])

In [160]:
np.concatenate([a,b], axis=1)

array([[ 0,  0,  1,  2],
       [ 1,  3,  4,  5],
       [ 2,  6,  7,  8],
       [ 3,  9, 10, 11],
       [ 4, 12, 13, 14]])

In [161]:
a = np.array([1,2,3])
b = np.array([[1,2,3], [4,5,6]])

In [162]:
np.vstack([a,b])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [163]:
np.concatenate([a,b], axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [164]:
a.shape, b.shape

((3,), (2, 3))

In [165]:
a = np.array([[1,2,3]])
b = np.array([[1,2,3], [4,5,6]])
np.concatenate([a,b], axis=0) # offers less flexibility

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [166]:
a.shape, b.shape

((1, 3), (2, 3))

# Fit Bit Case Study

In [167]:
import gdown
import numpy as np

In [168]:
!gdown 1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd

Downloading...
From: https://drive.google.com/uc?id=1vk1Pu0djiYcrdc85yUXZ_Rqq2oZNcohd
To: /content/fit.txt
100% 3.43k/3.43k [00:00<00:00, 11.9MB/s]


In [169]:
data = np.loadtxt('/content/fit.txt', dtype = 'str')

In [170]:
data.shape

(96, 6)

In [171]:
data.ndim

2

In [173]:
data

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [172]:
data[0]

array(['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
      dtype='<U10')

In [174]:
# display first 5 rows of data

data[:5]

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active']],
      dtype='<U10')

In [175]:
# Slicing

data[:,0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [176]:
data_2 = data.T
data_2[0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [177]:
#extract sleep into a separate column and covert its data type

sleep = data[:,4]
sleep = sleep.astype('int')
sleep.dtype

dtype('int64')

In [178]:
#extract step_count into a separate column and covert its data type

step_count = data[:,1]
step_count = step_count.astype('int')
step_count.dtype

dtype('int64')

In [179]:
#extract mood into a separate column and covert its data type

mood = data[:,2]
mood = mood.astype('str')
print(mood.dtype)
mood

<U10


array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [180]:
#extract calories_burned into a separate column and covert its data type

calories_burned = data[:,3]
calories_burned = calories_burned.astype('int')
calories_burned.dtype

dtype('int64')

In [181]:
#unique values in the mood column
m_uniq = np.unique(mood)
m_uniq

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

In [182]:
mood_h = np.where(mood == 'Happy', True, False)
mood_h

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False,  True])

Now let's look at something really interesting.

> **Can we extract the step counts, when the mood was Happy?**

In [183]:
step_count_happy = step_count[mood == 'Happy'].mean()
step_count_happy

3392.725

In [184]:
step_count_sad = step_count[mood == 'Sad'].mean()
step_count_sad

2103.0689655172414

In [185]:
# check the inverse of above using 4000 steps as threshold (check for 2000 steps as well)
mood_count_01 = mood[step_count > 3300]
mood_count_01

array(['Neutral', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad', 'Happy',
       'Sad', 'Neutral', 'Neutral', 'Neutral', 'Happy', 'Happy', 'Happy',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Sad', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Neutral', 'Neutral', 'Sad', 'Happy',
       'Neutral', 'Happy'], dtype='<U10')

In [186]:
c1 = np.count_nonzero(mood_count_01 == 'Happy')
print(c1)

23


In [187]:
mood_count_02 = mood[(step_count > 1800) & (step_count < 3300)]
mood_count_02

array(['Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Neutral', 'Happy'], dtype='<U10')

In [188]:
c2 = np.count_nonzero(mood_count_02 == 'Sad')
print(c2)

2
